# Generated by Django 2.2.7 on 2019-11-20 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='email',
        ),
    ]
