# Generated by Django 2.2.7 on 2019-11-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_remove_join_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
